# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = WaterDropDemo
QT += core gui widgets
CONFIG += debug

OBJECTS_DIR += debug
include(WaterDropDemo.pri)
